# Site
repository: sproogen/resume-theme
favicon: images/favicon.ico

darkmode: true


# Personal info
name: Elfarouk Harb
title: PhD Student at UIUC. 
description: Elfarouk Harb is a Quant Trader at Citadel Securities. Farouk Harb Citadel Securities. 
email: eyfmharb@gmail.com
website: https://github.com/FaroukY

# Social links
github_username:  FaroukY
# dribbble_username: jekyll
facebook_username: farouk.yasser.79
# flickr_username: jekyll
# instagram_username: chillwildlife
linkedin_username: elfarouky
# pinterest_username: jekyll
youtube_username: forallepsilon
# googleplus_username: +jekyll

gtag: "G-QFNG48LGYT"
# About Section
# about_title: About Me
about_profile_image: logo.png
about_content: | # this will include new lines to allow paragraphs
  Hi, my name is Farouk! I am a first year PhD student at the University of Illinois at Urbana Champaign in the CS theory group. I enjoy thinking about recreational math and combinatorial optimization problems. In my free time, I enjoy creating [Youtube](https://www.youtube.com/watch?v=XqTBrQYYUcc&ab_channel=ForAllEpsilon) videos about problem solving. Prior to joining UIUC, I worked at Citadel as a Quantitative Trader in the index arbitrage team.   

#Projects Section
projects_title: Publications and Projects

#Experience Section
experience_title: Experience

# Education Section
educaton_title: Education

# More Section
# more_title: A Little More About Me
more_content: | # this will include new lines to allow paragraphs
  Alongside my interests in software engineering and combinatorial optimization, some of my other interests and hobbies are:
   - Creating [Youtube](https://www.youtube.com/watch?v=XqTBrQYYUcc&ab_channel=ForAllEpsilon) videos
   - Gaming
   - Playing Chess

# Footer
footer_show_references: false

# Build settings
remote_theme: sproogen/resume-theme

sass:
  sass_dir: _sass
  style: compressed

plugins:
 - jekyll-seo-tag
